### ISSUE TITLE
sqrt is expensive

### ISSUE THREAD

**Issue by jacobsteffler** [team1306/Robot2019#1]
https://github.com/team1306/Robot2019/blob/4909708905dc5778ba4726f2c30cdaaf00169127/src/main/java/frc/robot/Robot.java#L103

The math here is pretty expensive. And also the line is just really long.
Even though it's not mathematically perfect, I would just check the X and Y axes separately.

If you do this, just be careful that the extreme case (stick at a 45 degree angle) works.
With the stick like that, both X and Y will be at 0.707, which is less that 0.75.

**Comment by EganJ** [comment]
Fixed.
