### ISSUE TITLE
Please clean up Network class

### ISSUE THREAD

**Issue by jacobsteffler** [team1306/Robot2019#2]
https://github.com/team1306/Robot2019/blob/4909708905dc5778ba4726f2c30cdaaf00169127/src/main/java/frc/robot/Network.java#L20

- Does this class need to be a [singleton](https://en.wikipedia.org/wiki/Singleton_pattern)?
- All of your class members should have access modifiers (public/private/protected)
- You should declare all members at the top of the class declaration (see testEntry)
- Please add more white s p a c e

**Comment by EganJ** [comment]
File was not necessary and has been deleted.
